# Site settings
remote-theme: freelancer-theme
title: djrobyay
email: me@djrobyay.me
url: https://djrobyay.me/
description: "Welcome to the House of yay! Home of soulful, funky, disco house grooves."
keywords: "house music, disco, disco house, soulful house, funky house, gay, gay dj, rob yay, djrobyay, robyay"
skills: "soulful, funky, disco house DJ"
meta_author: "DJ RobYAY"
google_verify: "V90PdanvvHT10Q7MMz_LgSf7RrjSnTLWPXjEogtDEco"
bing_verify: "18DDF7EFF4D39C2F37FE937ABA524350"
contact: static
# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: ''

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2590be
  primary-rgb: "37,144,190"
  secondary: 6c25be
  secondary-dark: 2b0f4c

# Footer settings
footer:
  copyright: djrobyay
  location: "On the earth:"
  social: "On the internets:"
  credits: "Don't forget what Diana Ross Says:"

social:
  - title: mixcloud
    url: https://mixcloud.com/djrobyay
  - title: house
    iconalt: solid
    url: https://www.house-mixes.com/profile/djrobyay
  - title: envelope
    iconalt: solid
    url: mailto:me@djrobyay.me
  - title: instagram
    url: https://www.instagram.com/djrobyay
  - title: twitter
    url: https://twitter.com/djrobyay

# Postal address (add as many lines as necessary)
address:
  - line: currently based in Las Vegas, NV, USA
  - line: willing to travel and to relocate
  - line: (nomadic by nature)

about:
  - line: "djrobyay is a rising star in the house music scene, hailing from Las Vegas with a passion for creating funky, soulful, and disco-infused mixes."
  - line: "rob was introduced to house music in 1996 at Junior Vasquez&#x27;s legendary Tunnel events in New York City. The infectious energy of the scene left a lasting impression, and he continued to explore the underground desert party scene in Southern California."
  - line: "Drawing inspiration from the likes of Dylan Drazen, Mark Farina, and Joe D&#x27;Espinosa, rob has been honing his new craft in private and for friends. Now, he&#x27;s ready to take his talents to the next level, seeking opportunities to spin publicly in LGBT-friendly spaces. His sets are characterized by their high-energy, feel-good vibes."
  - line: "With a deep love for the genre and a dedication to his craft, this new comer is poised to make a big impact on the house music scene. Keep an eye out for djrobyay as he brings his unique sound to a club or festival near you!"

# randomize fierce Diana Ross quotes
credits:
  - "We'd be better if the world just danced."

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
