# Site settings
title: djrobyay
email: me@djrobyay.me
url: https://djrobyay.me/
description: "Welcome to the House of yay! Home of soulful, funky, disco house grooves."
keywords: "house music, disco, disco house, soulful house, funky house, gay, gay dj, rob yay, djrobyay, robyay"
skills: "soulful, funky, disco house DJ"
meta_author: "DJ RobYAY"
google_verify:
bing_verify:
contact: static
# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: ''

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2590be
  primary-rgb: "37,144,190"
  secondary: 6c25be
  secondary-dark: 2b0f4c

# Footer settings
footer:
  copyright: djrobyay
  location: Location
  social: On the internets
  credits: "Diana Ross Says:"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: listen and stream at mixcloud
    url: https://mixcloud.com/djrobyay
  - title: listen, stream, and download at house-mixes.com
    url: https://www.house-mixes.com/profile/djrobyay
  - title: email me
    url: mailto:me@djrobyay.me
  - title: instagram
    url: https://www.instagram.com/djrobyay
  - title: twitter
    url: https://twitter.com/djrobyay

# Postal address (add as many lines as necessary)
address:
  - line: nomadic by nature
  - line: currently based in Las Vegas, NV, USA
  - line: willing to travel and to relocate

# Credits content
credits: "We'd be better if the world just danced."

# Build settings
markdown: kramdown
permalink: pretty

#sfor posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
